NUMBER_OF_COLUMNS: 25
COLUMNS:
  birth_rate: float
  business_tax_rate: object
  co2_emissions: float
  country: object
  days_to_start_business: float
  ease_of_business: float
  energy_usage: float
  gdp: object
  health_exp_percent_gdp: float
  health_expcapita: object
  hours_to_do_tax: float
  infant_mortality_rate: float
  internet_usage: float
  lending_interest: float
  life_expectancy_female: float
  life_expectancy_male: float
  mobile_phone_usage: float
  number_of_records: int
  population_014: float
  population_1564: float
  population_65: float
  population_total: int
  population_urban: float
  tourism_inbound: object
  tourism_outbound: object
